os: Visual Studio 2015

environment:
  HOME: "%HOMEDRIVE%%HOMEPATH%"
  PYTHON: C:\Python27
  SCONS_CACHE_ROOT: "%HOME%\\scons_cache"
  SCONS_CACHE_LIMIT: 512
  OPTIONS: target=release tools=no verbose=yes progress=no gdnative_wrapper=no use_lto=yes
  MODULES: module_bullet_enabled=yes module_dds_enabled=no module_enet_enabled=no module_etc_enabled=no module_freetype_enabled=yes module_gdnative_enabled=no module_gdscript_enabled=yes module_gridmap_enabled=no module_hdr_enabled=no module_jpg_enabled=no module_mobile_vr_enabled=no module_mono_enabled=no module_ogg_enabled=yes module_openssl_enabled=no module_opus_enabled=no module_pvr_enabled=no module_recast_enabled=no module_regex_enabled=no module_squish_enabled=no module_stb_vorbis_enabled=no module_svg_enabled=no module_tga_enabled=no module_thekla_unwrap_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_visual_script_enabled=no module_vorbis_enabled=yes module_webm_enabled=no module_webp_enabled=no
  matrix:
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GD_PLATFORM: windows
      TOOLS: no
      TARGET: release
      ARCH: amd64

cache:
  - "%SCONS_CACHE_ROOT%"

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install -U wheel  # needed for pip install scons to work, otherwise a flag is missing
  - pip install scons
  - if defined VS call "%VS%" %ARCH%  # if defined - so we can also use mingw

before_build:
  - echo %GD_PLATFORM%
  - python --version
  - scons --version
  - cl.exe
  - SET "SCONS_CACHE=%SCONS_CACHE_ROOT%\master"

build_script:
- scons platform=%GD_PLATFORM% target=%TARGET% tools=%TOOLS% %OPTIONS% %MODULES% disable_advanced_gui=yes
#- xcopy /s bin binsimpleui
#- scons platform=%GD_PLATFORM% target=%TARGET% tools=%TOOLS% %OPTIONS% %MODULES% disable_3d=yes
#- xcopy /s bin bin2d
#- scons platform=%GD_PLATFORM% target=%TARGET% tools=%TOOLS% %OPTIONS% %MODULES% disable_3d=yes disable_advanced_gui=yes
#- xcopy /s bin bin2dsimpleui

after_build:
- dir /s bin*
