language: cpp
dist: trusty
sudo: false
env:
  global:
  - SCONS_CACHE=$HOME/.scons_cache
  - SCONS_CACHE_LIMIT=1024
  - OPTIONS="target=release tools=no verbose=yes progress=no gdnative_wrapper=no use_llvm=yes"
  - MODULES="module_bullet_enabled=yes module_dds_enabled=no module_enet_enabled=no
    module_etc_enabled=no module_freetype_enabled=yes module_gdnative_enabled=no module_gdscript_enabled=yes
    module_gridmap_enabled=no module_hdr_enabled=no module_jpg_enabled=no module_mobile_vr_enabled=no
    module_mono_enabled=no module_ogg_enabled=yes module_openssl_enabled=no module_opus_enabled=no
    module_pvr_enabled=no module_recast_enabled=no module_regex_enabled=no module_squish_enabled=no
    module_stb_vorbis_enabled=no module_svg_enabled=no module_tga_enabled=no module_thekla_unwrap_enabled=no
    module_theora_enabled=no module_tinyexr_enabled=no module_visual_script_enabled=no
    module_vorbis_enabled=yes module_webm_enabled=no module_webp_enabled=no"
  - secure: QLFRizqry/Y5pnEZvDlQz5S3YydQ+600u4rHEzFgUTd0heYeQaETXAQeMzp0ymuG1BkdRAl5YJoLVJgAzjwI9hrvugvoUlh2//SfpqZCHN/Q1fYbtGgNTn01R3VFEpcfYQL93I2EjrxVm0WTM4PwCvMO+hU0aWTRDvCt1Lty0kMR+RMDQOO/woqunoXh5wvFNxTJJkAmuLe0v962DJYOIwJAnqMLR0aFYjmeQJ20bc/2X5oLt+WuJDuf/lGj6WSlD6z/o/kL3YxHoUyw4A/HAZ2IX0IfNHKuay60ESWzl/NlobnePiPwHAE2pdDVu//q16fanb9VeYnBYRFse49TpFRb86Lo+Qz8nKDJqpQEIY0YKNCFqekrubqTM++Lj6QvGpykQZNxUhybmELcEsRG4PS0UMvCpebdnJD46nNB+DtO2Lgb4xXDLQwpq19z1wizq/XDQ5hz61TIIx8+i8TsgdSQKCTeWovd4HcD4CVjAD5XTLGgyRmI/zC2d+lTnKo6W9diLq/bX/Goq2QPeaTPABqv817IaJka2JyugQ7Qal/+gNTjYRRsimRCL9B2tVh+Uh8rWhTFhQL4QbP5P65HF+p8qojUzqtAhPMbZ8mxUtNukUI3liVgPgiMss96sG0nTVglFgkkAkEjIMFnqMSKnTfG812K4jIhp2jCO2Q3NeI=
cache:
  directories:
  - "$SCONS_CACHE"
matrix:
  include:
  - env: GODOT_TARGET=x11 CACHE_NAME=${GODOT_TARGET}-clang
    os: linux
    compiler: clang
    addons:
      apt:
        packages:
          - libasound2-dev
          - libfreetype6-dev
          - libgl1-mesa-dev
          - libglu1-mesa-dev
          - libx11-dev
          - libxcursor-dev
          - libxi-dev
          - libxinerama-dev
          - libxrandr-dev
  - env: GODOT_TARGET=android CACHE_NAME=${GODOT_TARGET}-clang
    os: linux
    compiler: clang
  - env: GODOT_TARGET=osx CACHE_NAME=${GODOT_TARGET}-clang
    os: osx
    osx_image: xcode9.3
    compiler: clang
  - env: GODOT_TARGET=iphone CACHE_NAME=${GODOT_TARGET}-clang
    os: osx
    osx_image: xcode9.3
    compiler: clang
install:
- if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$GODOT_TARGET" = "android" ]; then misc/travis/android-tools-linux.sh;
  fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then misc/travis/scons-local-osx.sh; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$GODOT_TARGET" = "android" ]; then misc/travis/android-tools-osx.sh;
  fi
before_script:
- if [ "$GODOT_TARGET" = "android" ]; then export ANDROID_HOME=$TRAVIS_BUILD_DIR/godot-dev/build-tools/android-sdk;
  export ANDROID_NDK_ROOT=$TRAVIS_BUILD_DIR/godot-dev/build-tools/android-ndk; fi
script:
- scons -j2 CC=$CC CXX=$CXX platform=$GODOT_TARGET $EXTRA_ARGS $OPTIONS $MODULES disable_advanced_gui=yes
- if [ "$GODOT_TARGET" = "android" ]; then cd platform/android/java; ./gradlew build;
  ls -l bin; cd ../../..; fi
after_success:
- ls -l bin*
- if [ "$GODOT_TARGET" = "osx" ]; then cp -r misc/dist/osx_tools.app ./Godot.app;
  mkdir -p Godot.app/Contents/MacOS; cp bin/godot.osx.opt.64 Godot.app/Contents/MacOS/Godot;
  chmod +x Godot.app/Contents/MacOS/Godot; cp Godot.app bin; fi
deploy:
  provider: releases
  api_key:
    secure: Kq/T0hXSd4jbJgr79W4IBAD28zuEZvsiIKt01MaTu1NqEVHw9jNL9aHW1311n44oAQpsPAz9E37qFYNkcQurbuQn/Mo3cXNOpyCfRL7yDyVecd453zjcEUxCND1Qd9RRh+O/arGEsdTUQyQSmjQ7Pplg226ynPyeWSaeMQLhCeI7snKOGbPsvl7sCSYauS9lP+5k/hpkjno+c6IYVDkj8JldT0cvOdGiCNSqI4AjZQjVWeOtTr64cxIs/xeKY8L6gN9a/Qz7RdhYCJSbB06Qy9q2jUKICTnVqZZZheGU4751mkg+gc+CN43Em1E5eiYf2oGwe43g1jUTZsreCSkkr2hyzxfR+rGocfyXAkvpf+XK0MIySUFZjw22GFGeuLzYL5mxh9223rPEqZECBUTeyKj6aLgOyd1Gv7cIRQZWXab8x6TNX9SAECsBgwYA/bp/ISSHk3gdqxz6mUKGIWIJpxv0ZepOWlXZUMlgUlxgHPo11glxE+3VSup8aI6LHTDBcgBLfqO63CiD+Ph9Ds+VRwh8peqwlu4k6UW4ccac9MloFShLdumPO2uig//XzrlcMxY/jENIX+4HfXurtMUGkYiXKHL5ctU7a185lU+j9FDahMY8QJx0RtP22AoBcd1qRpbvJwVoPVIqkkjHZVQDwnSMZFEnHB4UUR4Kg+SvwUQ=
  file:
    - bin
  skip_cleanup: true
  draft: true
